namespace BrawlBusters.Core.Protocol;

public enum MsgCategory : byte
{
    Start = 0,

    sLoginFailed = 1,
    sCreateIDFailed = 2,
    sSessionInfo = 3,
    sStartSession = 4,
    sServer = 5,
    sUserStart = 6,
    sUserRestart = 7,
    sIntro = 8,
    sUserInfo = 9,
    sGlobalSync = 10,
    sInventory = 11,
    sStore = 12,
    sRoomList = 13,
    sMode = 14,
    sLobby = 15,
    sRoom = 16,
    sLadder = 17,
    sSinglePlay = 18,
    sUserRecords = 19,
    sHost = 20,
    sGame = 21,
    sObserver = 22,
    sUserMsg = 23,
    sTransServer = 24,
    sReward = 25,
    sNotice = 26,
    sError = 27,
    sRank = 28,
    sGMStart = 29,
    sCapsuleMachine = 30,
    sCommunity = 31,
    sChat = 32,
    sChatRoom = 33,
    sSecurity = 34,

    hsHostServerInfo = 35,
    hsHostServer = 36,
    lsHostServer = 37,

    cClientInfo = 38,
    cClientTransferInfo = 39,
    cClientInfo_Chatter = 40,
    cClientInfo_Host = 41,
    cSessionReady = 42,
    cServer = 43,
    cUserInfo = 44,
    cIntro = 45,
    cTutorial = 46,
    cInventory = 47,
    cStore = 48,
    cMode = 49,
    cLobby = 50,
    cRoom = 51,
    cLadder = 52,
    cSinglePlay = 53,
    cHost = 54,
    cGame = 55,
    cItem = 56,
    cUserMsg = 57,
    cUDP = 58,
    cCommand = 59,
    cDevCommand = 60,
    cRank = 61,
    cRecord = 62,
    cCapsuleMachine = 63,
    cCommunity = 64,
    cChat = 65,
    cChatRoom = 66,
    cSecurity = 67,

    gmClientInfo = 68,
    gmMsg = 69,
    gmCommand = 70,
    gmServerInfo = 71,
    gmGMStart = 72,
    gmGMEnd = 73,

    End = 74,
}
