namespace BrawlBusters.Core.Protocol;

public enum NetError : byte
{
    Invalid = 0,
    Success = 1,
    Unknown = 2,
    Login_PacketVersion = 3,
    Login_ClientVersion = 4,
    ServerInternal = 5,
    ID_InvalidName = 6,
    ID_TooShort = 7,
    ID_TooLong = 8,
    ID_InvalidChar = 9,
    ID_ExceedCharCount = 10,
    ID_AlreadyExist = 11,
    ID_Prohibited = 12,
    ID_AlreadyConnected = 13,
    ID_AnotherLogin = 14,
    ID_Unacceptable = 15,

    ID_ConnectionBlocked = 16,
    ID_NotExist = 17,
    ID_NotExist_OTP = 18,

    PW_WrongPassword = 19,
    PW_3Times_WrongPassword = 20,
    PW_TooShort = 21,
    PW_TooLong = 22,
    PW_SameAsID = 23,
    PW_AllSameChars = 24,
    PW_LinearString = 25,
    PW_NoSpecialChar = 26,
    Nick_TooShort = 27,
    Nick_TooLong = 28,
    Nick_InvalidChar = 29,
    Nick_DigitChar = 30,
    Nick_ExceedCount = 31,
    Nick_AlreadyExist = 32,
    Nick_Prohibited = 33,
    Nick_Active = 34,
    Nick_Unknown = 35,
    OTP_Failed = 36,
    LoginFailed = 37,
    MismatchHostVersion = 38,
    ServerTransfer = 39,
    ServerUDP = 40,
    RelayUDP = 41,
    HostConnectFailed = 42,
    HostDisconnected = 43,
    ServerConnectFailed = 44,
    ServerDisconnected = 45,
    NewServerConnectFailed = 46,
    ServerChangeFailed = 47,

    Lobby_FullRoomList = 71,
    Lobby_WrongPassword = 72,
    Lobby_CannotJoinRoom = 73,
    Lobby_NotExistRoom = 74,
    Lobby_ChangeChannel = 75,
    Lobby_ChannelFull = 76,
    Room_NetworkError = 80,
    Room_CantChangeTeam = 81,
    Room_InvalidLevelID = 82,
    Room_UserOut_GameCancel = 86,
    Room_InvalidRuleParamID = 101,
    Lobby_NotExistRoomInfo = 105,
    Room_CanNotIntrude = 110,
    Room_CanNotObserve = 111,
    Room_SwitchToObserver = 112,
    Room_SwitchToPlayer = 113,

    MyRecord_NotExistNick = 109,
    MyRecord_NoneMyRecord = 119,

    Chat_BuddyNotExist = 89,
    Chat_SelfBuddy = 90,
    Chat_AlreadyBuddy = 91,
    Chat_MyBuddyListFull = 96,
    Chat_TargetBuddyListFull = 97,
}
